Test deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -28,17 +28,24 @@ jobs:
       - name: Setup SSH
         run: |
           mkdir -p ~/.ssh
-          echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa  # Removes any carriage return characters
-          echo "Key Length: $(echo -n "${{ secrets.SSH_KEY }}" | wc -c)"  # Check length
+          # Outputting the key to file while ensuring proper formatting
+          echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
+
+          # Configure SSH
           echo "Host *" > ~/.ssh/config
           echo "    StrictHostKeyChecking no" >> ~/.ssh/config
           echo "    UserKnownHostsFile=/dev/null" >> ~/.ssh/config
           chmod 600 ~/.ssh/config
-
       - name: Check SSH Key Format
         run: |
           ssh-keygen -y -f ~/.ssh/id_rsa
+
+      - name: Debug SSH Key Format
+        run: |
+          echo "Key Length: $(echo -n "${{ secrets.SSH_KEY }}" | wc -c)"  # Check length
+          # Attempt to show public key derived from private key
+          ssh-keygen -y -f ~/.ssh/id_rsa || echo "Failed to read SSH key"
 
       - name: Deploy to EC2
         if: success()
